stages:
  - test
  - package
#  - packagetest
  - deploy

test:debian:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip python3-venv
    - python3 -m venv venv
    - venv/bin/pip install -r requirements.txt
    - venv/bin/python setup.py test
  tags:
    - debian


test:archlinux:
  stage: test
  script:
    - pacman -Sy python-pip python-setuptools python-virtualenv --noconfirm
    - virtualenv -p python3 venv
    - venv/bin/pip install .
    - venv/bin/pip install setuptools
    - venv/bin/python setup.py test
  tags:
    - archlinux

package:debian:
  stage: package
  script:
    - apt-get update -qy
    - apt-get install -y python3-git python3-stdeb git python3-docopt python3-yaml dh-python
    - rm -rf "./deb_dist"
    - python3 setup.py --command-packages=stdeb.command bdist_deb
  tags:
    - debian

  artifacts:
    paths:
      - deb_dist/*.deb
    expire_in: 1d

package:archlinux:
  stage: package
  script:
    - pacman -Sy sudo git python-gitpython python-yaml python-docopt fakeroot systemd binutils python-setuptools --noconfirm
    - useradd -m -G users -s /bin/bash package
    - chown -R package:users archlinux
    - cd archlinux
    - sudo -H -u package makepkg -f
  tags:
    - archlinux

  artifacts:
    paths:
      - archlinux/version*
    expire_in: 1d

#packagetest:debian:
#  stage: packagetest
#  script:
#    - apt-get update -qy
#    - cd deb_dist
#    - apt install ./*.deb -qy
#  tags:
#    - debian-systemd
#  dependencies:
#    - package:debian

#packagetest:archlinux:
#  stage: packagetest
#  script:
#    - pacman -Syu --noconfirm
#    - cd archlinux
#    - pacman -U version*.pkg.tar.zst --noconfirm
#  tags:
#    - archlinux-systemd
#  dependencies:
#    - package:archlinux

repoupdate:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/any/version*.pkg.tar.zst'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/version*.deb'
    - scp archlinux/version*.pkg.tar.zst www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/any
    - scp deb_dist/*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - ssh www-data@repository '/var/www/repository.salamek.cz/deb-pub-update.sh'
    - ssh www-data@repository '/var/www/repository.salamek.cz/arch-pub-update.sh'
  dependencies:
    - package:archlinux
    - package:debian
  tags:
    - docker
  only:
    - tags
