GIT:
    AUTO_COMMIT: true
    AUTO_TAG: true
    AUTO_PUSH: true
    COMMIT_MESSAGE: 'New version {version}'

VERSION_FILES:
    'version/__init__.py': 'VERSION\s*=\s*\(\s*(?P<major>\d+?)\s*\,\s*(?P<minor>\d+?)\s*\,\s*(?P<patch>\d+?)\s*\)'
    #'archlinux/PKGBUILD': 'pkgver\s*=\s*(?P<major>\d+?)\.(?P<minor>\d+?)\.(?P<patch>\d+?)'
    'archlinux/PKGBUILD': 'pkgver\s*=\s*(?P<version>.*)'
    '*/__init__.py': 'VERSION\s*=\s*\(\s*(?P<major>\d+?)\s*\,\s*(?P<minor>\d+?)\s*\,\s*(?P<patch>\d+?)\s*\)'
